Here's the _config.yml file content:

# Site settings
title: "Value Chain Hackers"
description: "Collaborative research community focused on sustainable supply chain innovation through transparent partnerships between academia and industry."
baseurl: "" # Empty for custom domain (valuechainhackers.xyz)
url: "https://valuechainhackers.xyz" # Custom domain URL
author: "Value Chain Hackers Team"

# Social media and contact
email: "info@valuechainhackers.xyz"
discord_url: "https://discord.gg/mkbjsQsV"
github_url: "https://github.com/ValueChainHackers"
linkedin_url: "https://www.linkedin.com/company/valuechainhackers/"
twitter_url: "https://twitter.com/valuechainhackers"

# Organization details
organization:
  name: "Value Chain Hackers"
  location: "Windesheim University, Zwolle, Netherlands"
  founded: 2023
  
# SEO and metadata
lang: en
timezone: Europe/Amsterdam

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections (for future expansion)
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  team:
    output: true
    permalink: /:collection/:name/
  events:
    output: true
    permalink: /:collection/:name/

# Default layouts for collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team-member"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore

# Include files
include:
  - _pages

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# GitHub Pages specific settings
github: [metadata]