name: Update News Feeds

on:
  schedule:
    # Run every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser pyyaml requests

      - name: Fetch and process RSS feeds
        run: python scripts/fetch_news_feeds.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _data/sustainability_news.yml _data/ai_news.yml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update news feeds [automated]" && git push)
